baseURL: https://rishabkumar.com
title: Rishab Kumar
paginate: 6
theme: charlolamode
googleAnalytics: "UA-141527833-1"



menu:
    main:
        - name: About
          url: about/
          weight: 30
        - name: Blog
          url: blog/
          weight: 20
        # - name: Categories
        #   url: categories/
        #   weight: 10
        - name: Notes
          url: https://notes.rishab.cloud
        #  weight: 10
        - name: Podcast
          url: podcast/


params:
    author: Rishab Kumar
    description: Hi, I am Rishab Kumar, a Developer Evangelist at Twilio and Cloud & DevOps enthusiast.


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Rishab Kumar 👋
        description: Ula
        imageUrl: "/images/profile.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
            - name: Checkout the DevOps Guide
              url: https://thedevops.guide
            - name: Subscribe to my newsletter
              url: https://rishabkumar.substack.com/
    mainSections:
      - articles

    socialIcons:
        - name: buymeacoffee
          url: "https://www.buymeacoffee.com/rishabincloud"
        - name: github
          url: "https://github.com/rishabkumar7"
        - name: linkedin
          url: "https://www.linkedin.com/in/rishabkumar7/"
        - name: twitter
          url: "https://twitter.com/rishabk7"
        - name: instagram
          url: "https://instagram.com/rishabincloud"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

